# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f0 = 0
f1 = 1
total = 0
maxiumum = 4000000
while f1 <= maxiumum:
  f1_Old = f1
  f1 = f0 + f1
  f0 = f1_Old
  if f1 % 2 == 0:
    total = total + f1
print str(total)
